package com.data_management;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

/**
 * Reads patient data from files generated by the HealthDataSimulator
 * and stores the parsed records in DataStorage.
 */
public class FileDataReader implements DataReader {
    private Path outputDirectory;
    private PatientDataParser parser;

    public FileDataReader(String outputDirectory) {
        this.outputDirectory = Path.of(outputDirectory);
        this.parser = new PatientDataParser();
    }

    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        try (Stream<Path> files = Files.list(outputDirectory)) {
            files.filter(Files::isRegularFile)
                    .forEach(file -> readFile(file, dataStorage));
        }
    }

    private void readFile(Path file, DataStorage dataStorage) {
        try (BufferedReader reader = Files.newBufferedReader(file)) {
            String line;

            while ((line = reader.readLine()) != null) {
                parseLine(line, dataStorage);
            }
        } catch (IOException e) {
            throw new RuntimeException("Could not read file: " + file, e);
        }
    }

    private void parseLine(String line, DataStorage dataStorage) {
        try {
            PatientRecord record = parser.parse(line);

            dataStorage.addPatientData(
                    record.getPatientId(),
                    record.getMeasurementValue(),
                    record.getRecordType(),
                    record.getTimestamp()
            );
        } catch (IllegalArgumentException e) {
            System.err.println("Skipping invalid line: " + line);
        }
    }
}