package com.data_management;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

/**
 * Reads patient data from files generated by the HealthDataSimulator
 * and stores the parsed records in DataStorage.
 *
 * Expected line format:
 * Patient ID: 29, Timestamp: 1778690404972, Label: Saturation, Data: 99.0%
 */
public class FileDataReader implements DataReader {
    private Path outputDirectory;

    public FileDataReader(String outputDirectory) {
        this.outputDirectory = Path.of(outputDirectory);
    }

    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        try (Stream<Path> files = Files.list(outputDirectory)) {
            files.filter(Files::isRegularFile)
                    .forEach(file -> readFile(file, dataStorage));
        }
    }

    private void readFile(Path file, DataStorage dataStorage) {
        try (BufferedReader reader = Files.newBufferedReader(file)) {
            String line;

            while ((line = reader.readLine()) != null) {
                parseLine(line, dataStorage);
            }
        } catch (IOException e) {
            throw new RuntimeException("Could not read file: " + file, e);
        }
    }

    private void parseLine(String line, DataStorage dataStorage) {
        if (line == null || line.isBlank()) {
            return;
        }

        try {
            String[] parts = line.split(",");

            if (parts.length != 4) {
                System.err.println("Skipping invalid line: " + line);
                return;
            }

            int patientId = parsePatientId(parts[0]);
            long timestamp = parseTimestamp(parts[1]);
            String recordType = parseRecordType(parts[2]);
            double measurementValue = parseMeasurementValue(parts[3]);

            dataStorage.addPatientData(patientId, measurementValue, recordType, timestamp);

        } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
            System.err.println("Skipping invalid line: " + line);
        }
    }

    private int parsePatientId(String part) {
        return Integer.parseInt(part.replace("Patient ID:", "").trim());
    }

    private long parseTimestamp(String part) {
        return Long.parseLong(part.replace("Timestamp:", "").trim());
    }

    private String parseRecordType(String part) {
        String label = part.replace("Label:", "").trim();

        if (label.equalsIgnoreCase("Saturation")) {
            return "BloodSaturation";
        }

        if (label.equalsIgnoreCase("Blood Pressure")) {
            return "BloodPressure";
        }

        return label;
    }

    private double parseMeasurementValue(String part) {
        String value = part.replace("Data:", "")
                .replace("%", "")
                .trim();

        return Double.parseDouble(value);
    }
}